server:
  port: 8761

spring:
  application:
    name: eureka-server
eureka:
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    # 是否注册当前eureka
    fetch-registry: false
    # 是否获取其他的EurekaServer服务的数据
    service-url:
      defaultZone: http://localhost:8761/eureka/
      # 注册中心的默认访问地址
  instance:
    prefer-ip-address: true